export const EMPLOYEE_PERMISSIONS = {
  EMPLOYEE_DASHBOARD_VIEW: 'EMPLOYEE_DASHBOARD_VIEW',

  USER_VERIFICATION_VIEW: 'USER_VERIFICATION_VIEW',
  USER_VERIFICATION_RECOMMEND: 'USER_VERIFICATION_RECOMMEND',
  USER_VERIFICATION_CORRECTION_REQUEST: 'USER_VERIFICATION_CORRECTION_REQUEST',

  PROPERTY_MODERATION_VIEW: 'PROPERTY_MODERATION_VIEW',
  PROPERTY_MODERATION_RECOMMEND: 'PROPERTY_MODERATION_RECOMMEND',
  PROPERTY_MODERATION_CORRECTION_REQUEST: 'PROPERTY_MODERATION_CORRECTION_REQUEST',

  ENQUIRY_VIEW: 'ENQUIRY_VIEW',
  ENQUIRY_UPDATE: 'ENQUIRY_UPDATE',
  CALL_NOTES_MANAGE: 'CALL_NOTES_MANAGE',

  VISIT_VIEW: 'VISIT_VIEW',
  VISIT_UPDATE: 'VISIT_UPDATE',

  FOLLOWUP_VIEW: 'FOLLOWUP_VIEW',
  FOLLOWUP_MANAGE: 'FOLLOWUP_MANAGE',

  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',
  INTERNAL_NOTES_VIEW: 'INTERNAL_NOTES_VIEW',
  INTERNAL_NOTES_MANAGE: 'INTERNAL_NOTES_MANAGE',

  REPORTS_VIEW: 'REPORTS_VIEW',
  EMPLOYEE_MANAGE: 'EMPLOYEE_MANAGE',
  ADMIN_SETTINGS_VIEW: 'ADMIN_SETTINGS_VIEW',

  VIEW_UNASSIGNED_RECORDS: 'VIEW_UNASSIGNED_RECORDS',
};

// Permissions an admin is allowed to grant/revoke on an employee record.
// EMPLOYEE_MANAGE and ADMIN_SETTINGS_VIEW are intentionally excluded — those
// stay admin-only regardless of what's ticked, since /admin/employees and
// /admin/settings are already role-gated to 'admin' and are not meant to
// ever become reachable by an employee account.
export const ASSIGNABLE_EMPLOYEE_PERMISSIONS = [
  EMPLOYEE_PERMISSIONS.EMPLOYEE_DASHBOARD_VIEW,
  EMPLOYEE_PERMISSIONS.USER_VERIFICATION_VIEW,
  EMPLOYEE_PERMISSIONS.USER_VERIFICATION_RECOMMEND,
  EMPLOYEE_PERMISSIONS.USER_VERIFICATION_CORRECTION_REQUEST,
  EMPLOYEE_PERMISSIONS.PROPERTY_MODERATION_VIEW,
  EMPLOYEE_PERMISSIONS.PROPERTY_MODERATION_RECOMMEND,
  EMPLOYEE_PERMISSIONS.PROPERTY_MODERATION_CORRECTION_REQUEST,
  EMPLOYEE_PERMISSIONS.ENQUIRY_VIEW,
  EMPLOYEE_PERMISSIONS.ENQUIRY_UPDATE,
  EMPLOYEE_PERMISSIONS.CALL_NOTES_MANAGE,
  EMPLOYEE_PERMISSIONS.VISIT_VIEW,
  EMPLOYEE_PERMISSIONS.VISIT_UPDATE,
  EMPLOYEE_PERMISSIONS.FOLLOWUP_VIEW,
  EMPLOYEE_PERMISSIONS.FOLLOWUP_MANAGE,
  EMPLOYEE_PERMISSIONS.NOTIFICATIONS_VIEW,
  EMPLOYEE_PERMISSIONS.INTERNAL_NOTES_VIEW,
  EMPLOYEE_PERMISSIONS.INTERNAL_NOTES_MANAGE,
  EMPLOYEE_PERMISSIONS.REPORTS_VIEW,
  EMPLOYEE_PERMISSIONS.VIEW_UNASSIGNED_RECORDS,
];

// Maps each employee route to the permission required to view it. Used by
// both the sidebar (to hide unauthorized modules) and RequirePermission
// (to block direct URL access) — a single source of truth for both.
export const EMPLOYEE_ROUTE_PERMISSIONS = {
  '/employee/dashboard': EMPLOYEE_PERMISSIONS.EMPLOYEE_DASHBOARD_VIEW,
  '/employee/verifications': EMPLOYEE_PERMISSIONS.USER_VERIFICATION_VIEW,
  '/employee/properties': EMPLOYEE_PERMISSIONS.PROPERTY_MODERATION_VIEW,
  '/employee/enquiries': EMPLOYEE_PERMISSIONS.ENQUIRY_VIEW,
  '/employee/visits': EMPLOYEE_PERMISSIONS.VISIT_VIEW,
  '/employee/follow-ups': EMPLOYEE_PERMISSIONS.FOLLOWUP_VIEW,
  '/employee/notifications': EMPLOYEE_PERMISSIONS.NOTIFICATIONS_VIEW,
  '/employee/reports': EMPLOYEE_PERMISSIONS.REPORTS_VIEW,
  '/employee/profile': null,
};
