export const DASHBOARD_NAV = {
  buyer: [
    { key: 'dashboard', path: '/buyer/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'properties', path: '/buyer/properties', labelKey: 'nav.browseProperties', icon: 'Search' },
    { key: 'my-properties', path: '/buyer/my-properties', labelKey: 'nav.myProperties', icon: 'Building2' },
    { key: 'interests', path: '/buyer/interests', labelKey: 'nav.interests', icon: 'MessageSquareHeart' },
    { key: 'documents', path: '/buyer/documents', labelKey: 'nav.myDocuments', icon: 'FolderOpen' },
    { key: 'bookings', path: '/buyer/bookings', labelKey: 'nav.bookings', icon: 'ClipboardList' },
    { key: 'visits', path: '/buyer/visits', labelKey: 'nav.myScheduledVisits', icon: 'CalendarCheck' },
    { key: 'notifications', path: '/buyer/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/buyer/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/buyer/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  seller: [
    { key: 'dashboard', path: '/seller/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'properties', path: '/seller/properties', labelKey: 'nav.myProperties', icon: 'Building2' },
    { key: 'new-property', path: '/seller/properties/new', labelKey: 'nav.addProperty', icon: 'PlusSquare' },
    { key: 'enquiries', path: '/seller/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox' },
    { key: 'visits', path: '/seller/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'analytics', path: '/seller/analytics', labelKey: 'profileMenu.analytics', icon: 'BarChart3' },
    { key: 'notifications', path: '/seller/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/seller/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/seller/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  mediator: [
    { key: 'dashboard', path: '/mediator/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'leads', path: '/mediator/leads', labelKey: 'nav.leads', icon: 'Users' },
    { key: 'purchases', path: '/mediator/purchases', labelKey: 'nav.purchases', icon: 'ShoppingBag' },
    { key: 'bookings', path: '/mediator/bookings', labelKey: 'nav.bookings', icon: 'ClipboardList' },
    { key: 'closed-deals', path: '/mediator/closed-deals', labelKey: 'nav.closedDeals', icon: 'Handshake' },
    { key: 'wallet', path: '/mediator/wallet', labelKey: 'nav.myWallet', icon: 'Wallet' },
    { key: 'bank-details', path: '/mediator/bank-details', labelKey: 'nav.bankDetails', icon: 'Landmark' },
    { key: 'documents', path: '/mediator/documents', labelKey: 'nav.documents', icon: 'FolderOpen' },
    { key: 'properties', path: '/mediator/properties', labelKey: 'nav.properties', icon: 'Building2' },
    { key: 'visits', path: '/mediator/visits', labelKey: 'nav.visits', icon: 'CalendarCheck' },
    { key: 'follow-ups', path: '/mediator/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall' },
    { key: 'commission', path: '/mediator/commission', labelKey: 'profileMenu.commissionHistory', icon: 'HandCoins' },
    { key: 'notifications', path: '/mediator/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'settings', path: '/mediator/settings', labelKey: 'nav.settings', icon: 'Settings' },
    { key: 'profile', path: '/mediator/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  employee: [
    { key: 'dashboard', path: '/employee/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard', permission: 'EMPLOYEE_DASHBOARD_VIEW' },
    { key: 'verifications', path: '/employee/verifications', labelKey: 'nav.verifications', icon: 'BadgeCheck', permission: 'USER_VERIFICATION_VIEW' },
    { key: 'properties', path: '/employee/properties', labelKey: 'nav.properties', icon: 'Building2', permission: 'PROPERTY_MODERATION_VIEW' },
    { key: 'enquiries', path: '/employee/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox', permission: 'ENQUIRY_VIEW' },
    { key: 'visits', path: '/employee/visits', labelKey: 'nav.visits', icon: 'CalendarCheck', permission: 'VISIT_VIEW' },
    { key: 'follow-ups', path: '/employee/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall', permission: 'FOLLOWUP_VIEW' },
    { key: 'notifications', path: '/employee/notifications', labelKey: 'nav.notifications', icon: 'Bell', permission: 'NOTIFICATIONS_VIEW' },
    { key: 'reports', path: '/employee/reports', labelKey: 'nav.reports', icon: 'BarChart3', permission: 'REPORTS_VIEW' },
    { key: 'profile', path: '/employee/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
  ],
  admin: [
    { key: 'dashboard', path: '/admin/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'registrations', path: '/admin/registrations', labelKey: 'nav.registrations', icon: 'UserPlus' },
    { key: 'users', path: '/admin/users', labelKey: 'nav.customers', icon: 'Users' },
    { key: 'employees', path: '/admin/employees', labelKey: 'nav.employees', icon: 'BadgeCheck' },
    { key: 'agents', path: '/admin/agents', labelKey: 'nav.agents', icon: 'IdCard' },
    { key: 'sales-members', path: '/admin/sales-members', labelKey: 'nav.salesMembers', icon: 'Briefcase' },
    { key: 'properties', path: '/admin/properties', labelKey: 'nav.properties', icon: 'Building2' },
    { key: 'categories', path: '/admin/categories', labelKey: 'nav.categories', icon: 'Tags' },
    { key: 'media-rules', path: '/admin/media-rules', labelKey: 'nav.mediaRules', icon: 'ImagePlus' },
    { key: 'cms', path: '/admin/cms', labelKey: 'nav.cms', icon: 'FileText' },
    { key: 'enquiries', path: '/admin/enquiries', labelKey: 'nav.enquiries', icon: 'Inbox' },
    { key: 'contact-messages', path: '/admin/contact-messages', labelKey: 'nav.contactMessages', icon: 'Mail' },
    { key: 'express-interests', path: '/admin/express-interests', labelKey: 'nav.expressInterests', icon: 'MessageSquareHeart' },
    { key: 'purchases', path: '/admin/purchases', labelKey: 'nav.purchases', icon: 'ShoppingBag' },
    { key: 'closed-deals', path: '/admin/closed-deals', labelKey: 'nav.closedDeals', icon: 'Handshake' },
    { key: 'wallet-redemptions', path: '/admin/wallet-redemptions', labelKey: 'nav.walletRedemptions', icon: 'Wallet' },
    { key: 'wallet-reports', path: '/admin/wallet-reports', labelKey: 'nav.walletReports', icon: 'HandCoins' },
    { key: 'documents', path: '/admin/documents', labelKey: 'nav.documentHistory', icon: 'FolderOpen' },
    { key: 'bookings', path: '/admin/bookings', labelKey: 'nav.bookings', icon: 'ClipboardList' },
    { key: 'map-plots', path: '/admin/map-plots', labelKey: 'nav.mapPlots', icon: 'Map' },
    { key: 'visits', path: '/admin/visits', labelKey: 'nav.siteVisitManagement', icon: 'CalendarCheck' },
    { key: 'promotions', path: '/admin/promotions', labelKey: 'nav.promotions', icon: 'Megaphone' },
    { key: 'follow-ups', path: '/admin/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall' },
    { key: 'reports', path: '/admin/reports', labelKey: 'nav.reports', icon: 'BarChart3' },
    { key: 'notifications', path: '/admin/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'audit-logs', path: '/admin/audit-logs', labelKey: 'nav.auditLogs', icon: 'History' },
    { key: 'profile', path: '/admin/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
    {
      key: 'settings',
      path: '/admin/settings',
      labelKey: 'nav.settings',
      icon: 'Settings',
      children: [
        { key: 'settings-general', path: '/admin/settings', labelKey: 'nav.generalSettings', icon: 'SlidersHorizontal', end: true },
        { key: 'hero-slides', path: '/admin/settings/hero-slides', labelKey: 'nav.heroSlides', icon: 'Images' },
      ],
    },
  ],
  sales_member: [
    { key: 'dashboard', path: '/sales/dashboard', labelKey: 'nav.dashboard', icon: 'LayoutDashboard' },
    { key: 'customers', path: '/sales/customers', labelKey: 'nav.customers', icon: 'Users' },
    { key: 'agents', path: '/sales/agents', labelKey: 'nav.agents', icon: 'IdCard' },
    { key: 'leads', path: '/sales/leads', labelKey: 'nav.leads', icon: 'MessageSquareHeart' },
    { key: 'visits', path: '/sales/visits', labelKey: 'nav.siteVisitManagement', icon: 'CalendarCheck' },
    { key: 'contact-messages', path: '/sales/contact-messages', labelKey: 'nav.contactMessages', icon: 'Mail' },
    { key: 'follow-ups', path: '/sales/follow-ups', labelKey: 'nav.followUps', icon: 'PhoneCall' },
    { key: 'bookings', path: '/sales/bookings', labelKey: 'nav.bookings', icon: 'ClipboardList' },
    { key: 'purchases', path: '/sales/purchases', labelKey: 'nav.purchases', icon: 'ShoppingBag' },
    { key: 'closed-deals', path: '/sales/closed-deals', labelKey: 'nav.closedDeals', icon: 'Handshake' },
    { key: 'properties', path: '/sales/properties', labelKey: 'nav.properties', icon: 'Building2' },
    { key: 'notifications', path: '/sales/notifications', labelKey: 'nav.notifications', icon: 'Bell' },
    { key: 'profile', path: '/sales/profile', labelKey: 'nav.profile', icon: 'UserCircle' },
    { key: 'settings', path: '/sales/settings', labelKey: 'nav.settings', icon: 'Settings' },
  ],
};

DASHBOARD_NAV.customer = DASHBOARD_NAV.buyer;
DASHBOARD_NAV.agent = DASHBOARD_NAV.mediator;

export const ROLE_HOME = {
  buyer: '/buyer/dashboard',
  customer: '/buyer/dashboard',
  agent: '/mediator/dashboard',
  seller: '/seller/dashboard',
  mediator: '/mediator/dashboard',
  employee: '/',
  admin: '/admin/dashboard',
  sales_member: '/sales/dashboard',
};

/** Default post-login route when no return URL or pending action exists. */
export function getPostLoginDestination(role) {
  if (role === 'admin') return ROLE_HOME.admin;
  return '/';
}
