import { useEffect, useState } from 'react';
import { FileText, Award, Eye } from 'lucide-react';
import { expressInterestService } from '../../services/expressInterestService';
import PaymentReceiptDocument from '../../components/purchases/PaymentReceiptDocument';
import SaleCertificateDocument from '../../components/purchases/SaleCertificateDocument';
import { toast } from '../../store/toastStore';

function money(n) {
  return `₹${Number(n || 0).toLocaleString('en-IN')}`;
}

function fmtDate(value) {
  if (!value) return '—';
  return new Date(value).toLocaleString();
}

/**
 * My Documents / Document History — payment receipts + sale certificates.
 * @param {'customer'|'admin'|'agent'} scope
 */
export default function DocumentsPanel({ scope = 'customer' }) {
  const [docs, setDocs] = useState({ paymentReceipts: [], saleCertificates: [] });
  const [loading, setLoading] = useState(true);
  const [viewingPayment, setViewingPayment] = useState(null);
  const [viewingCert, setViewingCert] = useState(null);

  function load() {
    setLoading(true);
    expressInterestService
      .listDocuments()
      .then(setDocs)
      .catch((err) => {
        setDocs({ paymentReceipts: [], saleCertificates: [] });
        toast.error(err.message || 'Failed to load documents');
      })
      .finally(() => setLoading(false));
  }

  useEffect(load, []);

  async function openPaymentReceipt(id, action = 'VIEW') {
    try {
      const data = await expressInterestService.getPaymentReceipt(id, action);
      setViewingPayment(data);
    } catch (err) {
      toast.error(err.message || 'Receipt not found');
    }
  }

  async function openSaleCertificate(id, action = 'VIEW') {
    try {
      const data = await expressInterestService.getSaleCertificate(id, action);
      setViewingCert(data);
    } catch (err) {
      toast.error(err.message || 'Certificate not found');
    }
  }

  const title = scope === 'admin'
    ? 'Document History'
    : scope === 'agent'
      ? 'Deal Documents'
      : 'My Documents';

  const subtitle = scope === 'admin'
    ? 'All payment receipts and sale certificates generated by the system.'
    : scope === 'agent'
      ? 'Read-only payment receipts and sale certificates for your assigned deals.'
      : 'Payment receipts and property sale certificates for your purchases.';

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-bold text-brand-800">{title}</h1>
        <p className="mt-1 text-sm text-gray-500">{subtitle}</p>
      </div>

      {loading ? (
        <p className="text-sm text-gray-500">Loading documents…</p>
      ) : (
        <>
          <section className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            <div className="flex items-center gap-2 border-b border-gray-100 px-4 py-3">
              <FileText size={16} className="text-brand-700" />
              <h2 className="font-semibold text-brand-800">Payment Receipts</h2>
              <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
                {docs.paymentReceipts?.length || 0}
              </span>
            </div>
            {!docs.paymentReceipts?.length ? (
              <p className="px-4 py-6 text-sm text-gray-500">No payment receipts yet.</p>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-100 text-sm">
                  <thead className="bg-gray-50 text-left text-xs uppercase text-gray-500">
                    <tr>
                      <th className="px-4 py-2">Receipt #</th>
                      <th className="px-4 py-2">Date</th>
                      <th className="px-4 py-2">Amount</th>
                      <th className="px-4 py-2">Status</th>
                      <th className="px-4 py-2">Refs</th>
                      <th className="px-4 py-2">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {docs.paymentReceipts.map((r) => (
                      <tr key={r.id} className="hover:bg-gray-50/80">
                        <td className="px-4 py-2 font-mono text-xs">{r.number}</td>
                        <td className="px-4 py-2 text-xs">{fmtDate(r.date)}</td>
                        <td className="px-4 py-2 font-medium">{money(r.amount)}</td>
                        <td className="px-4 py-2">
                          <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${r.status === 'FULL' ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>
                            {r.status === 'FULL' ? 'Full Payment' : 'Partial Payment'}
                          </span>
                        </td>
                        <td className="px-4 py-2 font-mono text-xs text-gray-500">
                          {r.purchaseRequestId ? `PR-${r.purchaseRequestId}` : ''}
                          {r.bookingRequestId ? ` BK-${r.bookingRequestId}` : ''}
                        </td>
                        <td className="px-4 py-2">
                          <button
                            type="button"
                            onClick={() => openPaymentReceipt(r.id)}
                            className="inline-flex items-center gap-1 rounded border border-gray-200 px-2 py-1 text-xs font-medium hover:bg-gray-50"
                          >
                            <Eye size={12} /> View
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          <section className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            <div className="flex items-center gap-2 border-b border-gray-100 px-4 py-3">
              <Award size={16} className="text-brand-700" />
              <h2 className="font-semibold text-brand-800">Sale Certificates</h2>
              <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
                {docs.saleCertificates?.length || 0}
              </span>
            </div>
            {!docs.saleCertificates?.length ? (
              <p className="px-4 py-6 text-sm text-gray-500">No sale certificates yet. Certificates are generated when a purchase is fully completed.</p>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-100 text-sm">
                  <thead className="bg-gray-50 text-left text-xs uppercase text-gray-500">
                    <tr>
                      <th className="px-4 py-2">Certificate #</th>
                      <th className="px-4 py-2">Generated</th>
                      <th className="px-4 py-2">Sale Date</th>
                      <th className="px-4 py-2">Purchase</th>
                      <th className="px-4 py-2">Status</th>
                      <th className="px-4 py-2">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {docs.saleCertificates.map((c) => (
                      <tr key={c.id} className="hover:bg-gray-50/80">
                        <td className="px-4 py-2 font-mono text-xs">{c.number}</td>
                        <td className="px-4 py-2 text-xs">{fmtDate(c.date)}</td>
                        <td className="px-4 py-2 text-xs">{fmtDate(c.saleDate)}</td>
                        <td className="px-4 py-2 font-mono text-xs">PR-{c.purchaseRequestId}</td>
                        <td className="px-4 py-2">
                          <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-semibold text-emerald-800">
                            {c.status || 'ACTIVE'}
                          </span>
                        </td>
                        <td className="px-4 py-2">
                          <button
                            type="button"
                            onClick={() => openSaleCertificate(c.id)}
                            className="inline-flex items-center gap-1 rounded border border-gray-200 px-2 py-1 text-xs font-medium hover:bg-gray-50"
                          >
                            <Eye size={12} /> View
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>
        </>
      )}

      {viewingPayment && (
        <PaymentReceiptDocument
          receipt={viewingPayment}
          onClose={() => setViewingPayment(null)}
          onAction={(action) => openPaymentReceipt(viewingPayment.id, action)}
        />
      )}
      {viewingCert && (
        <SaleCertificateDocument
          certificate={viewingCert}
          onClose={() => setViewingCert(null)}
          onAction={(action) => openSaleCertificate(viewingCert.id, action)}
        />
      )}
    </div>
  );
}
